version: '3'
services:
  frontend1:
    build:
      context: './frontend'
    
    command: '/opt/frontend --backend backend:8081'

    ports:
      - 8000:8080
  
  frontend2:
    build:
      context: './frontend'

    command: '/opt/frontend --listen :8082 --backend backend:8081'

    ports:
      - 8001:8082


  backend:
    build:
      context: './backend'